name: human_ai
description: "Human AI Application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_neumorphic_plus: ^3.4.0
  flutter_spinkit: ^5.1.0
  flutter_riverpod: ^2.4.6
  dio: ^5.3.2
  json_annotation: ^4.8.1

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/